package routes

import (
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger/v2"
	"net/http"
	"rest-api/controller"
	_ "rest-api/docs" // docs is generated by Swag CLI, you have to import it.
	"rest-api/middleware"
)

func InitRoutes(userController *controller.UserController) *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	router.Use(middleware.BasicAuth)
	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://localhost:3000/swagger/doc.json"),
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"))).Methods(http.MethodGet)
	router.HandleFunc("/user", userController.Save).Methods(http.MethodPost)
	router.HandleFunc("/user", userController.FindAll).Methods(http.MethodGet)
	router.HandleFunc("/user/{id}", userController.FindById).Methods(http.MethodGet)
	return router
}
